// Design System Tokens — Prevalent AI
// AUTO-GENERATED by scripts/build-tokens.js — do not edit manually
// Source: ds/tokens/colors.json · ds/tokens/spacing.json · ds/tokens/typography.json
// Run `npm run build:tokens` to regenerate after changing ds/tokens/*.json

export const colors = {
  primary: {
    default: '#6360D8',
    hover: '#504bb8',
    pressed: '#6360D8',
    disabled: '#F5F5F5',
    light: '#f0f0fc',
    border: '#6360D8',
  },
  primarySpecial: {
    gradientFrom: '#467fcd',
    gradientTo: '#47adcb',
    border: '#b1b8f5',
    hoverBg: 'rgba(177,184,245,0.2)',
    pressedBg: 'rgba(177,184,245,0.3)',
    pressedBorder: '#7e8aee',
  },
  secondary: {
    default: '#f0f0fc',
    hover: '#e0dff7',
    text: '#6360D8',
    hoverText: '#504bb8',
    pressed: '#6360D8',
  },
  success: {
    default: '#EFF7ED',
    hover: '#d6f1df',
    pressed: '#d6f1df',
    pressedBorder: '#31A56D',
    text: '#1a7549',
    pressedText: '#0a4a2c',
  },
  danger: {
    default: '#F9EEEE',
    hover: '#ffdbdc',
    pressed: '#ffdbdc',
    pressedBorder: '#eb8e90',
    text: '#D12329',
    pressedText: '#931b1f',
  },
  warning: {
    default: '#FEF3C7',
    text: '#D98B1D',
  },
  severity: {
    critical: {
      text: '#D12329',
      bg: '#F9EEEE',
    },
    high: {
      text: '#D98B1D',
      bg: '#FEF3C7',
    },
    medium: {
      text: '#6360D8',
      bg: '#f0f0fc',
    },
    low: {
      text: '#31A56D',
      bg: '#EFF7ED',
    },
  },
  neutral: {
    text: '#282828',
    textDark: '#101010',
    disabled: '#9CA3AF',
    border: '#CFCFCF',
    borderLight: '#E6E6E6',
    bg: '#F5F5F5',
    bgDark: '#E6E6E6',
  },
  shell: {
    '--shell-bg': '#F7F9FC',
    '--shell-border': '#E6E6E6',
    '--shell-text': '#101010',
    '--shell-text-2': '#282828',
    '--shell-text-muted': '#6E6E6E',
    '--shell-accent': '#6360D8',
    '--shell-hover': 'rgba(0,0,0,0.04)',
    '--shell-active': 'rgba(99,96,216,0.08)',
    '--shell-raised': '#F5F5F5',
    '--ctrl-bg': '#FFFFFF',
    '--ctrl-border': '#CFCFCF',
    '--ctrl-placeholder': '#9CA3AF',
    '--card-bg': '#FFFFFF',
    '--card-border': '#E6E6E6',
    '--table-th-bg': '#F5F5F5',
    '--table-border': '#E6E6E6',
  },
};

export const typography = {
  fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif',
  monoFamily: 'SF Mono, Fira Code, monospace',
  baseSize: '12px',
  scale: {
    'page-title': {
      fontSize: '18px',
      fontWeight: 700,
    },
    'heading-md': {
      fontSize: '14px',
      fontWeight: 600,
    },
    'subheader-title': {
      fontSize: '12px',
      fontWeight: 500,
    },
    'body-md': {
      fontSize: '12px',
      fontWeight: 400,
    },
    'body-sm': {
      fontSize: '11px',
      fontWeight: 400,
    },
  },
  tailwindScale: {
    '2xs': {
      size: '10px',
      'line-height': '14px',
    },
    xs: {
      size: '11px',
      'line-height': '15px',
    },
    sm: {
      size: '12px',
      'line-height': '16px',
    },
    base: {
      size: '13px',
      'line-height': '19px',
    },
    md: {
      size: '14px',
      'line-height': '20px',
    },
    lg: {
      size: '16px',
      'line-height': '22px',
    },
    xl: {
      size: '18px',
      'line-height': '24px',
    },
  },
};

export const spacing = {
  '2xs': '4px',
  xs: '8px',
  sm: '12px',
  md: '16px',
  lg: '20px',
  xl: '24px',
  '2xl': '32px',
  '3xl': '48px',
};

export const borderRadius = {
  button: '44px',
  card: '4px',
  badge: '4px',
  input: '8px',
  dropdown: '8px',
  modal: '12px',
};

export const chartColors = ['#6360D8', '#47adcb', '#31A56D', '#D12329', '#D98B1D'];

export const chartTheme = {
  tooltip: {
    bg: '#FFFFFF',
    border: '#CFCFCF',
    text: '#282828',
    radius: '4px',
  },
  axis: {
    tick: '#9CA3AF',
    grid: '#F5F5F5',
  },
  legend: {
    dotSize: 8,
    text: '#282828',
    fontSize: '12px',
  },
};
