/**
 * Icon registry — lucide-react icons organized by category.
 * Each entry: { name: string (lucide component name), label: string }
 */
export const ICON_REGISTRY = {
  Navigation: [
    { name: 'Home', label: 'Home' },
    { name: 'LayoutDashboard', label: 'Dashboard' },
    { name: 'Menu', label: 'Menu' },
    { name: 'ArrowLeft', label: 'Arrow Left' },
    { name: 'ArrowRight', label: 'Arrow Right' },
    { name: 'ArrowUp', label: 'Arrow Up' },
    { name: 'ArrowDown', label: 'Arrow Down' },
    { name: 'ChevronLeft', label: 'Chevron Left' },
    { name: 'ChevronRight', label: 'Chevron Right' },
    { name: 'ChevronUp', label: 'Chevron Up' },
    { name: 'ChevronDown', label: 'Chevron Down' },
    { name: 'ExternalLink', label: 'External Link' },
    { name: 'Link', label: 'Link' },
    { name: 'MoreHorizontal', label: 'More Horizontal' },
    { name: 'MoreVertical', label: 'More Vertical' },
  ],
  Actions: [
    { name: 'Plus', label: 'Add' },
    { name: 'Minus', label: 'Minus' },
    { name: 'X', label: 'Close' },
    { name: 'Check', label: 'Check' },
    { name: 'Edit', label: 'Edit' },
    { name: 'Edit2', label: 'Edit 2' },
    { name: 'Trash', label: 'Delete' },
    { name: 'Trash2', label: 'Delete 2' },
    { name: 'Copy', label: 'Copy' },
    { name: 'Download', label: 'Download' },
    { name: 'Upload', label: 'Upload' },
    { name: 'Share', label: 'Share' },
    { name: 'Share2', label: 'Share 2' },
    { name: 'RefreshCw', label: 'Refresh' },
    { name: 'Search', label: 'Search' },
    { name: 'Filter', label: 'Filter' },
    { name: 'SortAsc', label: 'Sort Asc' },
    { name: 'SortDesc', label: 'Sort Desc' },
    { name: 'Save', label: 'Save' },
    { name: 'Send', label: 'Send' },
  ],
  Status: [
    { name: 'CheckCircle', label: 'Success' },
    { name: 'CheckCircle2', label: 'Success 2' },
    { name: 'XCircle', label: 'Error' },
    { name: 'AlertCircle', label: 'Warning' },
    { name: 'AlertTriangle', label: 'Alert' },
    { name: 'Info', label: 'Info' },
    { name: 'HelpCircle', label: 'Help' },
    { name: 'Loader', label: 'Loader' },
    { name: 'Loader2', label: 'Loader 2' },
    { name: 'Clock', label: 'Pending' },
    { name: 'Ban', label: 'Blocked' },
    { name: 'Shield', label: 'Shield' },
    { name: 'ShieldCheck', label: 'Shield Check' },
  ],
  UI: [
    { name: 'Eye', label: 'View' },
    { name: 'EyeOff', label: 'Hide' },
    { name: 'Lock', label: 'Lock' },
    { name: 'Unlock', label: 'Unlock' },
    { name: 'Settings', label: 'Settings' },
    { name: 'Sliders', label: 'Sliders' },
    { name: 'Bell', label: 'Notification' },
    { name: 'BellOff', label: 'Notification Off' },
    { name: 'Sun', label: 'Light Mode' },
    { name: 'Moon', label: 'Dark Mode' },
    { name: 'Maximize', label: 'Expand' },
    { name: 'Minimize', label: 'Collapse' },
    { name: 'Maximize2', label: 'Fullscreen' },
    { name: 'Minimize2', label: 'Exit Fullscreen' },
    { name: 'Grid', label: 'Grid' },
    { name: 'List', label: 'List' },
    { name: 'Columns', label: 'Columns' },
    { name: 'Sidebar', label: 'Sidebar' },
    { name: 'Panel', label: 'Panel' },
    { name: 'Layers', label: 'Layers' },
  ],
  Data: [
    { name: 'BarChart2', label: 'Bar Chart' },
    { name: 'PieChart', label: 'Pie Chart' },
    { name: 'LineChart', label: 'Line Chart' },
    { name: 'TrendingUp', label: 'Trending Up' },
    { name: 'TrendingDown', label: 'Trending Down' },
    { name: 'Activity', label: 'Activity' },
    { name: 'Database', label: 'Database' },
    { name: 'Table', label: 'Table' },
    { name: 'FileText', label: 'File Text' },
    { name: 'File', label: 'File' },
    { name: 'Folder', label: 'Folder' },
    { name: 'FolderOpen', label: 'Folder Open' },
    { name: 'Tag', label: 'Tag' },
    { name: 'Tags', label: 'Tags' },
    { name: 'Hash', label: 'Hash' },
  ],
  User: [
    { name: 'User', label: 'User' },
    { name: 'Users', label: 'Users' },
    { name: 'UserCheck', label: 'User Check' },
    { name: 'UserPlus', label: 'User Add' },
    { name: 'UserMinus', label: 'User Remove' },
    { name: 'UserX', label: 'User Remove' },
    { name: 'LogIn', label: 'Login' },
    { name: 'LogOut', label: 'Logout' },
    { name: 'Mail', label: 'Email' },
    { name: 'Phone', label: 'Phone' },
    { name: 'AtSign', label: 'At' },
    { name: 'Key', label: 'Key' },
  ],
};

export const ALL_ICONS = Object.values(ICON_REGISTRY).flat();
export const CATEGORIES = Object.keys(ICON_REGISTRY);
